GestioneAssenze/Models/Assenza.cs
using System;
using System.Collections.Generic;

namespace GestioneAssenze.Models;

public partial class Assenza
{
    public int Id { get; set; }

    public DateTime? Data { get; set; }

    public string Tipo { get; set; } = null!;

    public string Matrstudente { get; set; } = null!;

    public int Iddocente { get; set; }

    public TimeSpan? Ora { get; set; }

    public string Durata { get; set; } = null!;

    public virtual Docente IddocenteNavigation { get; set; } = null!;

    public virtual Studente MatrstudenteNavigation { get; set; } = null!;
}

GestioneAssenze/Models/Classe.cs
using System;
using System.Collections.Generic;

namespace GestioneAssenze.Models;

public partial class Classe
{
    public int Id { get; set; }

    public string Nome { get; set; } = null!;

    public string Tipologia { get; set; } = null!;

    public string Indirizzo { get; set; } = null!;

    public virtual ICollection<Lezione> Leziones { get; set; } = new List<Lezione>();

    public virtual ICollection<Studente> Studentes { get; set; } = new List<Studente>();
}

GestioneAssenze/Models/Docente.cs
using System;
using System.Collections.Generic;

namespace GestioneAssenze.Models;

public partial class Docente
{
    public int Id { get; set; }

    public string Nome { get; set; } = null!;

    public string Cognome { get; set; } = null!;

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public virtual ICollection<Assenza> Assenzas { get; set; } = new List<Assenza>();

    public virtual ICollection<Svolge> Svolges { get; set; } = new List<Svolge>();
}

GestioneAssenze/Models/ErrorViewModel.cs
namespace GestioneAssenze.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GestioneAssenze/Models/Lezione.cs
using System;
using System.Collections.Generic;

namespace GestioneAssenze.Models;

public partial class Lezione
{
    public int Id { get; set; }

    public DateTime Data { get; set; }

    public TimeSpan Ora { get; set; }

    public string Materia { get; set; } = null!;

    public string? Argomento { get; set; }

    public int Idclasse { get; set; }

    public virtual Classe IdclasseNavigation { get; set; } = null!;

    public virtual ICollection<Svolge> Svolges { get; set; } = new List<Svolge>();
}

GestioneAssenze/Models/Studente.cs
using System;
using System.Collections.Generic;

namespace GestioneAssenze.Models;

public partial class Studente
{
    public string Matricola { get; set; } = null!;

    public string Nome { get; set; } = null!;

    public string Cognome { get; set; } = null!;

    public DateTime Datanascita { get; set; }

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public int Idclasse { get; set; }

    public virtual ICollection<Assenza> Assenzas { get; set; } = new List<Assenza>();

    public virtual Classe IdclasseNavigation { get; set; } = null!;
}

GestioneAssenze/Models/Svolge.cs
using System;
using System.Collections.Generic;

namespace GestioneAssenze.Models;

public partial class Svolge
{
    public int Iddocente { get; set; }

    public int Idlezione { get; set; }

    public string? Tipologia { get; set; }

    public virtual Docente IddocenteNavigation { get; set; } = null!;

    public virtual Lezione IdlezioneNavigation { get; set; } = null!;
}

GestioneAssenze/Controllers/AssenzeController.cs
using GestioneAssenze.Models;
using Microsoft.AspNetCore.Mvc;

namespace GestioneAssenze.Controllers
{
    public class AssenzeController : Controller
    {
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("matricola") == null)       //se non c'è loggato nessuno mostro la pagina di login
                return RedirectToAction("Login","Home");
            else
                using (ScuolaContext context = new ScuolaContext())
                {
                    DateTime inizioAnno = new DateTime(DateTime.Now.Year, 1, 1);
                    List<Assenza> elencoAssenze =
                        context.Assenzas.Where(a => a.Data>= inizioAnno &&
                        a.Matrstudente== HttpContext.Session.GetString("matricola")
                                     ).ToList();
                    ViewData["nomestudente"] = HttpContext.Session.GetString("nomestudente");
                    return View(elencoAssenze);
                }
           
        }
    }
}

GestioneAssenze/Controllers/HomeController.cs
using GestioneAssenze.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestioneAssenze.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("matricola") ==null)       //se non c'è loggato nessuno mostro la pagina di login
                return RedirectToAction("Login");
            else
            {
                ViewData["nomestudente"] = HttpContext.Session.GetString("nomestudente");
                return View();
            }
                
        }


        [HttpGet]
        public IActionResult Login()     //pagina /Home/Login       (richiesta pagina di login)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(Studente studente)     //pagina /Home/Login (richiesta post quando l'utente clicca sul bottone login. In user ci sarà la username e la password)
        {
            using (ScuolaContext dbContext = new ScuolaContext())
            {
                Studente? loggedUser = dbContext.Studentes
                    .Where(u => 
                        u.Username==studente.Username && 
                        u.Password==studente.Password)      //cerco nel db un utente con username e password specificati
                    .FirstOrDefault();
                if (loggedUser == null)
                    return NotFound("Nome utente o password errata");
                else  //utente trovato=>lo memorizzo nella sessione
                {
                    //memorizzo il nome dell'utente all'interno della sessione
                    HttpContext.Session.SetString("matricola",loggedUser.Matricola);
                    HttpContext.Session.SetString("nomestudente", loggedUser.Nome + " "+loggedUser.Cognome);
                    
                    return RedirectToAction("Index"); //vado sulla pagina principale
                }

            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("matricola");
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GestioneAssenze/Views/Assenze/Index.cshtml
@model List<Assenza>


<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Data</th>
                <th>Tipo</th>
                <th>Ora</th>
                <th>Durata</th>
            </tr>     
        </thead>
        <tbody>
            @foreach(Assenza a in Model)
            {
                <tr>
                    <td>
                        @String.Format("{0:d}",a.Data)
                    </td>
                    <td>
                        @a.Tipo
                    </td>
                    <td>
                        @if(a.Ora!=null)
                        {
                            @a.Ora
                        } 
                    </td>
                    <td>
                        @a.Durata
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

GestioneAssenze/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Gestione assenze";
}

<div class="text-center">
    <h1 class="display-4">Gestione assenze</h1>
   
</div>

GestioneAssenze/Views/Home/Login.cshtml
@model Studente

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1>Please login</h1>
            </div>
            <form asp-controller="Home" asp-action="Login" method="post">
                <div class="mb-3">
                    <strong>Username:</strong>
                    <input asp-for="Username" class="d-block" />
                </div>
                <div class="mb-3">
                    <strong>Password:</strong>
                    <input type="password" asp-for="Password" class="d-block" />
                </div>

                <button class="btn btn-primary" type="submit">Login</button>

            </form>

        </div>
    </div>
</div>

GestioneAssenze/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestioneAssenze</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestioneAssenze.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestioneAssenze</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assenze" asp-action="Index">Assenze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
                <div>
                    @ViewData["nomestudente"]
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GestioneAssenze - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>